# Generated by Django 5.1.3 on 2025-06-24 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tags", models.CharField(blank=True, max_length=120, null=True)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                ("first", models.CharField(max_length=50, null=True)),
                ("last", models.CharField(max_length=50, null=True)),
                (
                    "city",
                    models.CharField(
                        max_length=120,
                        null=True,
                        verbose_name="City  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[ NA if Not Applicable ]",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        max_length=50,
                        null=True,
                        verbose_name="State/Province/Region  &nbsp;&nbsp;&nbsp;&nbsp;[ NA if Not Applicable ]",
                    ),
                ),
                ("country", models.CharField(max_length=80, null=True)),
                (
                    "zipcode",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Zip/Postal Code",
                    ),
                ),
                (
                    "email_incidents",
                    models.BooleanField(
                        default=True,
                        verbose_name="Email Me When Incidents Are Reported In My Area",
                    ),
                ),
                ("position", models.CharField(max_length=80, null=True)),
                (
                    "created_with",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("oauth_data", models.TextField(blank=True, null=True)),
                ("can_blog", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserBlogProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "byline",
                    models.CharField(
                        max_length=150,
                        null=True,
                        verbose_name="Byline (how your name should appear)",
                    ),
                ),
                (
                    "about_the_author",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="If you want an 'About The Author' section",
                    ),
                ),
                (
                    "up",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blogprofile",
                        to="users.userprofile",
                    ),
                ),
            ],
        ),
    ]
