# Generated by Django 5.1.3 on 2025-10-09 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE auth_user ALTER COLUMN last_login DROP NOT NULL;",
            reverse_sql="ALTER TABLE auth_user ALTER COLUMN last_login SET NOT NULL;",
        ),
    ]
