# Generated by Django 5.1.3 on 2025-11-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_fix_last_login_null"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpammerBlacklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "normalized_email",
                    models.CharField(db_index=True, max_length=254, unique=True),
                ),
                (
                    "email_variations",
                    models.TextField(
                        default="[]", help_text="JSON array of email variations"
                    ),
                ),
                (
                    "ip_addresses",
                    models.TextField(
                        default="[]", help_text="JSON array of IP addresses"
                    ),
                ),
                (
                    "usernames",
                    models.TextField(default="[]", help_text="JSON array of usernames"),
                ),
                (
                    "reason",
                    models.CharField(default="spam_registration", max_length=255),
                ),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                (
                    "hit_count",
                    models.IntegerField(
                        default=1, help_text="Number of times they've tried to register"
                    ),
                ),
            ],
            options={
                "verbose_name": "Spammer Blacklist Entry",
                "verbose_name_plural": "Spammer Blacklist",
                "ordering": ["-last_seen"],
            },
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="city",
            field=models.CharField(
                max_length=120,
                null=True,
                verbose_name="City     [ NA if Not Applicable ]",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="state",
            field=models.CharField(
                max_length=50,
                null=True,
                verbose_name="State/Province/Region    [ NA if Not Applicable ]",
            ),
        ),
    ]
