# Generated by Django 5.1.3 on 2025-11-12 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_spammerblacklist_alter_userprofile_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="profile_completed",
            field=models.BooleanField(default=False),
        ),
    ]
