# Generated by Django 5.1.3 on 2025-06-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(blank=True, max_length=120, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('amazon_asin', models.CharField(help_text='Amazon Standard Identification Number', max_length=20, unique=True)),
                ('amazon_url', models.URLField(help_text='Full Amazon product URL', max_length=500)),
                ('category', models.CharField(choices=[('tires', 'Tires'), ('helmets', 'Helmets'), ('cameras', 'Cameras'), ('lights', 'Lights'), ('accessories', 'Accessories'), ('safety', 'Safety Equipment')], max_length=50)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
