# Generated by Django 5.1.3 on 2025-11-12 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinput",
            name="website",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Website"
            ),
        ),
    ]
