# Generated by Django 5.1.3 on 2025-11-14 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_userinput_website"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpamTrapEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_normalized",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("email_raw", models.CharField(blank=True, max_length=255)),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, db_index=True, null=True),
                ),
                ("user_agent", models.CharField(blank=True, max_length=512)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("contact", "Contact Form"),
                            ("registration", "Registration"),
                            ("manual", "Manual Entry"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=32,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("payload_excerpt", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
