# Generated by Django 5.1.3 on 2025-06-24 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tldr", models.CharField(blank=True, max_length=250, null=True)),
                ("tags", models.CharField(blank=True, max_length=120, null=True)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                ("the_announcement", models.TextField()),
                ("show_it", models.BooleanField(default=False)),
                ("start_on_date", models.DateField(blank=True, null=True)),
                ("end_on_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Announcement",
                "verbose_name_plural": "Announcements",
                "ordering": ["-start_on_date", "-created"],
            },
        ),
        migrations.CreateModel(
            name="InTheNews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tldr", models.CharField(blank=True, max_length=250, null=True)),
                ("tags", models.CharField(blank=True, max_length=120, null=True)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                ("zipcode", models.CharField(blank=True, max_length=20, null=True)),
                ("city", models.CharField(blank=True, max_length=80, null=True)),
                ("state", models.CharField(blank=True, max_length=80, null=True)),
                ("country", models.CharField(blank=True, max_length=80, null=True)),
                ("title", models.CharField(max_length=150)),
                ("summary", models.TextField()),
                ("url", models.CharField(blank=True, max_length=250, null=True)),
                ("occurred_on", models.DateField(blank=True, null=True)),
                ("report_on", models.DateField(blank=True, null=True)),
                ("source", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "show_it",
                    models.BooleanField(
                        default=False, verbose_name="Publish/Make Visible at site"
                    ),
                ),
            ],
            options={
                "verbose_name": "In The News",
                "verbose_name_plural": "In The News",
                "ordering": ["-report_on", "-created"],
            },
        ),
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tldr", models.CharField(blank=True, max_length=250, null=True)),
                ("tags", models.CharField(blank=True, max_length=120, null=True)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                ("title", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(null=True)),
                ("the_post", models.TextField(null=True)),
                ("publish_date", models.DateField(blank=True, null=True)),
                ("reviewed", models.BooleanField(default=False)),
                ("post_is_public", models.BooleanField(default=True)),
                (
                    "publish_it",
                    models.BooleanField(
                        default=False, verbose_name="Publish This Post"
                    ),
                ),
                (
                    "social_buttons",
                    models.BooleanField(
                        default=True, verbose_name="Show Social-Sharing Buttons"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog Post",
                "verbose_name_plural": "Blog Posts",
                "ordering": ["-created"],
            },
        ),
    ]
